version: 2
jobs:
  build:
    docker:
      - image: k4zuki/pandocker
    steps:
      - checkout
      - run:
          name: get submodule
          command: |
            git submodule update --init
            export CURRENT_TAG=`git rev-parse --short HEAD`
      - run:
          name: Update tags in sch/brd files
          # TODO: replace "tag-updater" by proper name
          command: |
            mkdir -p deploy
            git clone https://github.com/K4zuki/myPCBlib.git tag-updater
            # for fname in `ls *.sch *.brd`; do python3 tag-updater/eagle-commit-update.py --tag $CURRENT_TAG $fname ; done
            for fname in `ls *.sch *.brd`; do echo $fname ; done

      - run:
          name: Deploy preparation
          command: |
            mkdir deploy
            zip deploy/$CIRCLE_PROJECT_REPONAME-$CURRENT_TAG *-$CURRENT_TAG.brd *-$CURRENT_TAG.sch

      - run:
          name: Deploy
          command: ghr -replace -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME build-$CURRENT_TAG deploy/
